### ISSUE TITLE
CMD + / not working

### ISSUE THREAD

**Issue by dal95** [HubSpot/hubspot-cms-vscode#113]
After updating to the latest version, the comment shortcut no longer working if the filetype is set to HTML + HUBL. 
It works when I change it to HUBL only, but the syntax highlighting is broken this time.

I noticed there are these new changes [here](https://github.com/HubSpot/hubspot-cms-vscode/pull/111). Is there any instruction to make this feature work like it used to be?

**Comment by johnsfuller** [comment]
I can confirm this too

**Comment by anthmatic** [comment]
Sorry about that, I did merge some fixes in but they got published under an older version number for some reason. I just published version 0.13.0 which fixes this bug.
