### ISSUE TITLE
scope_css throws error

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/hubspot-cms-vscode#116]
Reported via Slack:

`Invalid usage of 'scope_css': Could not find a wrapping HTML ID to scope the CSS to. 'scope_css' can only be used within modules.`

**Comment by carlosguisan** [comment]
Same issue when I try to write a custom module
![image](https://user-images.githubusercontent.com/2250265/143474354-0cf27406-294a-4c71-aa36-cdf0f6cd21bf.png)

**Comment by dperolio** [comment]
Seems to still be an issue in 2022, getting the same error.

**Comment by anthmatic** [comment]
I was able to reproduce this issue on Windows and a fix has been release in the latest version of the extension.
