### ISSUE TITLE
Should variables (or any curly brace things) contain or not contain the braces?

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-vscode#13]
Currently for functions I do not include the braces, but for variables I am including the brace. Should I include them or not?

The language congif makes it really easy to wrap things in curly braces, and it is annoying to delete them when you are using them within HubL already.

**Comment by brandenrodgers** [comment]
We will keep as-is for now, but we can revisit if this turns out to be a pain point
