### ISSUE TITLE
How can I run my website locally for development?

### ISSUE THREAD

**Issue by joehbenti** [HubSpot/hubspot-cms-vscode#131]
Am using VS code for development. any help would be appreciated. Thank you

**Comment by powerbuoy** [comment]
You can't run a HS site locally, you need to upload it to HS. You can [create a free developer account](https://developers.hubspot.com/get-started) and then use [HS CLI](https://developers.hubspot.com/docs/cms/developer-reference/local-development-cli) to sync your local files to a HS account though. More here: https://developers.hubspot.com/docs/cms/guides/getting-started
