### ISSUE TITLE
Typo on the listing

### ISSUE THREAD

**Issue by bradhave94** [HubSpot/hubspot-cms-vscode#261]
**Describe the bug**
Under the *IntelliSense Suggestions* heading

> If you **are** would like to get IntelliSense suggestions when in snippet placeholders, you will need to add the following to your user settings:

should be

> If you would like to get IntelliSense suggestions when in snippet placeholders, you will need to add the following to your user settings:

**To Reproduce**
1. Go to [the listing](https://marketplace.visualstudio.com/items?itemName=hubspot.hubl)
3. Scroll down to [IntelliSense Suggestions](https://marketplace.visualstudio.com/items?itemName=hubspot.hubl#intellisense-suggestions)

**Comment by j-malt** [comment]
Hey Brad, thanks for reporting. This is fixed as part of #260.
