### ISSUE TITLE
Looks like the New Module command doesn't work as expected

### ISSUE THREAD

**Issue by m0zz094** [HubSpot/hubspot-cms-vscode#271]
**Describe the bug**
As per title, the command to create a new module from vscode is not working correctly, it's creating an additional useless folder (.module) inside the module folder (module.module)

![bug](https://github.com/user-attachments/assets/5e41849c-3bf9-4ba3-a94c-3aec8c4fcd53)

**Comment by AnthonyPerez13** [comment]
Running into the same issue, I'd recommend downgrading back to 1.2.2 until a fix has been rolled out

**Comment by jsines** [comment]
Hello, fix for this was merged and will be in the next version (with ~a few days)!
