### ISSUE TITLE
Module shortcut fields.json error

### ISSUE THREAD

**Issue by johnsfuller** [HubSpot/hubspot-cms-vscode#64]
in module fields.json files, there is incorrect formatting for `help_text` and `inline_help_text` json. Those options are outside of every field or group created.

**Comment by williamspiro** [comment]
Thanks for filing this!

Looks like these have broke with https://github.com/HubSpot/hubspot-cms-vscode/commit/a64eb7bb55ca4817c732d8bfac9c20f2c5cbbc37#diff-870887b3dede6654487df29a373b0cb2

This was also reported here https://hubspotdev.slack.com/archives/CLJJXGTC0/p1598398703015900
