### ISSUE TITLE
Command + / comment behavior

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-vscode#65]
Currently, `cmd + /` will wrap you selection in a HubL comment. This is happening across all file types.

Do we want this behavior to occur across all languages? Do we want it to be configurable? What if you are working outside of the context of HubSpot CMS?

**Comment by gcorne** [comment]
Here is some info on default keybindings: https://code.visualstudio.com/docs/getstarted/keybindings#_default-keyboard-shortcuts.

**Comment by williamspiro** [comment]
This might actually only be happening in HTML and CSS testing again

**Comment by miketalley** [comment]
Fixed with https://github.com/HubSpot/hubspot-cms-vscode/issues/65
