### ISSUE TITLE
Split language support away from HTML and into HUBL-CSS and HUBL-HTML

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/hubspot-cms-vscode#71]
Currently, the extension works for HTML, CSS, and JS files but that's not ideal for developers that work on non-HS projects. 

For HTML and CSS files (purposefully excluding JS):
- we should activate the extension
- test for hubl
- offer to change the file association for the particular project

We should also make sure that this is documented (the language types vs file extension, and how to set this for project/user in VSCode)

Most of this work will happen in #69

**Comment by jsines** [comment]
This is no longer relevant, closing in favor of https://github.com/HubSpot/hubspot-cms-vscode/issues/229
