### ISSUE TITLE
CSS indentation and auto-complete does not work in CSS + HubL files

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-vscode#92]
Similar to https://github.com/HubSpot/hubspot-cms-vscode/issues/87, some of the useful features of CSS files in Visual Studio code, like auto-indentation and auto-complete, do not work in CSS + HubL files

![indent](https://user-images.githubusercontent.com/35824747/99282049-37bacf00-2801-11eb-9d23-40bbeccda66c.gif)

cc @HubSpot/cms-developer-experience

**Comment by anthmatic** [comment]
Potential path forward here https://github.com/microsoft/vscode/issues/73559

**Comment by tbl-droid** [comment]
Auto completion still doesn't really seem to work. When working in normal css mode I get completions for css properties (like background-color) and custom defined css variables. With css + hubl I don't get these. I tried adding css in the emmet.includeLanguages like:
```

"emmet.includeLanguages": {
    "html-hubl": "html",
    "css-hubl": "css"
  }
```
  
  This sort of helped. It allows certain css emmet abbreviations like bgc for background-color, but typing "back" for example only yields the hubl background_color and site_settings.background_color as a completions.
