### ISSUE TITLE
There is no formatter for 'html-hubl' files installed

### ISSUE THREAD

**Issue by SkyComplete** [HubSpot/hubspot-cms-vscode#97]
I'm trying to format HTML files `ALT+SHIFT+F` after they've been associated with html-hubl but it's giving me this error: `There is no formatter for 'html-hubl' files installed`.

Syntax highlighting works but not formatting.

I tried to define the vscode HTML formatter for html-hub files but it didn't make a difference.  Here's what I have in my settings.json file

```
    "files.associations": {
        "*.html": "html-hubl",
        "*.css": "css-hubl",
    },
    "[html-hubl]": {
        "editor.defaultFormatter": "vscode.html-language-features",
    },

```

Maybe I'm using the wrong field name when trying to defile the language `"[html-hubl]"`? Is the hyphen in the file type breaking that setting somehow?

**Comment by anthmatic** [comment]
@SkyComplete thank you for filing this issue and apologies for not getting back to you sooner. It looks like the built-in HTML formatted is fairly rigid and we're not able to enable if for HubL files. That said, even if it is enabled, it doesn't handle HubL tags particularly well. 

I don't have a timeline, but we would like to look into creating a Prettier plugin to offer syntax formatting: https://github.com/HubSpot/hubspot-cli/issues/279
